### ISSUE TITLE
What is the max VRAM requirements / usage for inference?

### ISSUE THREAD

**Issue by oxysoft** [deepmind/tapnet#22]
Hello! It seems the front page is missing this very crucial information, without it nobody knows if they can run it or not and I may waste a lot of time setting up the repository only to find out it doesn't fit.

Cheers!

**Comment by yangyi02** [comment]
Thank you for the feedback. From what I saw, the inference may take 12GB GPU memory for the demo in the colab.

<img width="716" alt="Screenshot 2023-06-18 at 11 30 20 AM" src="https://github.com/deepmind/tapnet/assets/4534987/27449151-5301-4c4c-9394-66d65e246057">

**Comment by cdoersch** [comment]
It's not easy to give a single nuber because it depends heavily on what you're trying to do.  The live demo (which runs on a 480x480 image runs fine on my 8GB M4000 even when I limit JAX to 0.05% of the memory via `XLA_PYTHON_CLINENT_MEM_FRACTION=0.05` (which still somehow allocates 1GB of memory; there's probably another flag I need to tweak).  But obviously, more points, larger frames, and longer videos processed in batch mode, you can easily end up with a tensor that takes the whole memory.  

I agree that we should add a bit more info on memory usage, but JAX doesn't make it super easy as it tends to only be careful about freeing tensors when memory is limited, so we can't just look at overall usage.  However, almost any discrete GPU (in fact, almost any GPU in general) should be able to run something (e.g. 1 frame at a time at 256x256), and even CPU mode is decently fast for small images.
